# Generated by Django 6.0 on 2025-12-17 18:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='author',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='mention',
            name='external_id',
            field=models.CharField(default=api.models.gen_external_id, max_length=40),
        ),
        migrations.AddField(
            model_name='mention',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_source_external_id'),
        ),
    ]
